# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PRIVATE_TARGET = "server"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
