import { NextResponse } from "next/server";
import { connectToDB } from "@/components/lib/mongodb";
import Product from "@/components/models/Products";

export async function POST() {
  try {
    await connectToDB();

    // Delete all existing products for a clean slate
    await Product.deleteMany({});

    const products = [
      // HELMET CATEGORY
      {
        id: "helmet-1",
        name: "Urban Commuter Helmet",
        title: "Urban Commuter Helmet",
        category: "helmet",
        price: 49.99,
        originalPrice: 59.99,
        discount: "17%",
        stockCount: 20,
        inStock: true,
        rating: 4.7,
        reviews: 120,
        description:
          "Lightweight, stylish helmet for city rides with excellent ventilation and comfort.",
        features: [
          "Lightweight design",
          "Adjustable straps",
          "Ventilated",
          "Reflective elements",
          "Certified safety",
        ],
        specifications: {
          Material: "Polycarbonate",
          Weight: "300g",
          Size: "M/L",
          Safety: "CPSC Certified",
        },
        label: "POPULAR",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        images: [
          "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "helmet-2",
        name: "Mountain Pro Helmet",
        title: "Mountain Pro Helmet",
        category: "helmet",
        price: 69.99,
        originalPrice: 89.99,
        discount: "22%",
        stockCount: 15,
        inStock: true,
        rating: 4.8,
        reviews: 98,
        description:
          "Rugged helmet designed for mountain biking adventures with advanced protection.",
        features: [
          "Shock absorbent",
          "GoPro mount",
          "Sun visor",
          "Extra padding",
          "MIPS technology",
        ],
        specifications: {
          Material: "ABS",
          Weight: "350g",
          Size: "L/XL",
          Safety: "MIPS Certified",
        },
        label: "NEW",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
        images: [
          "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "helmet-3",
        name: "Kids Safety Helmet",
        title: "Kids Safety Helmet",
        category: "helmet",
        price: 29.99,
        originalPrice: 39.99,
        discount: "25%",
        stockCount: 30,
        inStock: true,
        rating: 4.6,
        reviews: 45,
        description:
          "Colorful, safe helmet designed specifically for children with fun designs.",
        features: [
          "Fun designs",
          "Lightweight",
          "Easy fit",
          "Certified safe",
          "Adjustable",
        ],
        specifications: {
          Material: "EPS",
          Weight: "200g",
          Size: "S",
          Safety: "CPSC Certified",
        },
        label: "SALE",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
        images: [
          "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "helmet-4",
        name: "Classic Road Helmet",
        title: "Classic Road Helmet",
        category: "helmet",
        price: 59.99,
        originalPrice: 69.99,
        discount: "14%",
        stockCount: 10,
        inStock: true,
        rating: 4.5,
        reviews: 60,
        description:
          "Aerodynamic helmet optimized for road cycling with excellent ventilation.",
        features: [
          "Aerodynamic",
          "Sweat-wicking",
          "Lightweight",
          "Durable",
          "Wind tunnel tested",
        ],
        specifications: {
          Material: "Polycarbonate",
          Weight: "280g",
          Size: "M/L",
          Safety: "CE Certified",
        },
        label: "PREMIUM",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #43cea2 0%, #185a9d 100%)",
        images: [
          "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=600&h=600&fit=crop",
        ],
      },

      // BIKE CATEGORY
      {
        id: "bike-1",
        name: "City Cruiser Bike",
        title: "City Cruiser Bike",
        category: "bike",
        price: 299.99,
        originalPrice: 349.99,
        discount: "14%",
        stockCount: 8,
        inStock: true,
        rating: 4.8,
        reviews: 210,
        description:
          "Comfortable city bike perfect for daily commutes with upright riding position.",
        features: [
          "7-speed",
          "Comfort saddle",
          "Lightweight frame",
          "Mudguards",
          "Basket included",
        ],
        specifications: {
          Frame: "Aluminum",
          Gears: "7",
          Weight: "12kg",
          Size: "M/L",
        },
        label: "HOT",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)",
        images: [
          "https://images.unsplash.com/photo-1518655048521-f130df041f66?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "bike-2",
        name: "Mountain Explorer",
        title: "Mountain Explorer",
        category: "bike",
        price: 499.99,
        originalPrice: 599.99,
        discount: "17%",
        stockCount: 5,
        inStock: true,
        rating: 4.9,
        reviews: 180,
        description:
          "Durable mountain bike built for off-road trails and adventure riding.",
        features: [
          "21-speed",
          "Front suspension",
          "Disc brakes",
          "Wide tires",
          "Shock absorption",
        ],
        specifications: {
          Frame: "Steel",
          Gears: "21",
          Weight: "15kg",
          Size: "L/XL",
        },
        label: "NEW",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)",
        images: [
          "https://images.unsplash.com/photo-1465101178521-c1a9136a3b41?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "bike-3",
        name: "Folding Travel Bike",
        title: "Folding Travel Bike",
        category: "bike",
        price: 399.99,
        originalPrice: 449.99,
        discount: "11%",
        stockCount: 12,
        inStock: true,
        rating: 4.7,
        reviews: 95,
        description:
          "Compact folding bike for easy storage and convenient travel.",
        features: [
          "Foldable",
          "Lightweight",
          "6-speed",
          "Carry bag included",
          "Quick fold",
        ],
        specifications: {
          Frame: "Aluminum",
          Gears: "6",
          Weight: "11kg",
          Size: "One size",
        },
        label: "POPULAR",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
        images: [
          "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "bike-4",
        name: "Electric Commuter Bike",
        title: "Electric Commuter Bike",
        category: "bike",
        price: 899.99,
        originalPrice: 999.99,
        discount: "10%",
        stockCount: 6,
        inStock: true,
        rating: 4.6,
        reviews: 70,
        description:
          "Eco-friendly electric bike for fast and efficient city travel.",
        features: [
          "Electric motor",
          "Removable battery",
          "LED display",
          "Disc brakes",
          "Pedal assist",
        ],
        specifications: {
          Frame: "Aluminum",
          Battery: "36V",
          Range: "40km",
          Motor: "250W",
        },
        label: "PREMIUM",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
        images: [
          "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=600&h=600&fit=crop",
        ],
      },

      // ACCESSORIES CATEGORY
      {
        id: "accessory-1",
        name: "LED Bike Light Set",
        title: "LED Bike Light Set",
        category: "accessories",
        price: 19.99,
        originalPrice: 24.99,
        discount: "20%",
        stockCount: 40,
        inStock: true,
        rating: 4.8,
        reviews: 150,
        description:
          "Front and rear LED lights for safe night riding with multiple modes.",
        features: [
          "USB rechargeable",
          "Waterproof",
          "Easy mount",
          "Bright LEDs",
          "Multiple modes",
        ],
        specifications: {
          Battery: "USB",
          Lumens: "200",
          Modes: "4",
          Runtime: "6 hours",
        },
        label: "SALE",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #43cea2 0%, #185a9d 100%)",
        images: [
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "accessory-2",
        name: "Bike Phone Mount",
        title: "Bike Phone Mount",
        category: "accessories",
        price: 14.99,
        originalPrice: 19.99,
        discount: "25%",
        stockCount: 25,
        inStock: true,
        rating: 4.7,
        reviews: 80,
        description:
          "Secure phone mount for navigation and tracking on the go.",
        features: [
          "360° rotation",
          "Universal fit",
          "Shockproof",
          "Easy install",
          "Anti-vibration",
        ],
        specifications: {
          Material: "ABS",
          Weight: "80g",
          Size: "Universal",
          "Max Phone": "6.5 inch",
        },
        label: "POPULAR",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)",
        images: [
          "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "accessory-3",
        name: "Cycling Water Bottle",
        title: "Cycling Water Bottle",
        category: "accessories",
        price: 9.99,
        originalPrice: 12.99,
        discount: "23%",
        stockCount: 60,
        inStock: true,
        rating: 4.6,
        reviews: 110,
        description:
          "Lightweight, BPA-free water bottle designed for cyclists.",
        features: [
          "BPA-free",
          "Easy squeeze",
          "Leak-proof",
          "600ml",
          "Insulated",
        ],
        specifications: {
          Material: "Plastic",
          Capacity: "600ml",
          Color: "Black",
          Weight: "120g",
        },
        label: "NEW",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)",
        images: [
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "accessory-4",
        name: "Bike Lock",
        title: "Bike Lock",
        category: "accessories",
        price: 24.99,
        originalPrice: 29.99,
        discount: "17%",
        stockCount: 35,
        inStock: true,
        rating: 4.5,
        reviews: 90,
        description:
          "Heavy-duty lock to keep your bike secure with combination protection.",
        features: [
          "Steel cable",
          "Combination lock",
          "Weatherproof",
          "Portable",
          "Anti-theft",
        ],
        specifications: {
          Material: "Steel",
          Length: "1.2m",
          Weight: "400g",
          Security: "Level 8",
        },
        label: "HOT",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
        images: [
          "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=600&h=600&fit=crop",
        ],
      },

      // KEYCHAINS CATEGORY
      {
        id: "keychain-1",
        name: "Bike Chain Keychain",
        title: "Bike Chain Keychain",
        category: "keychains",
        price: 7.99,
        originalPrice: 9.99,
        discount: "20%",
        stockCount: 50,
        inStock: true,
        rating: 4.7,
        reviews: 60,
        description:
          "Unique keychain made from real bike chain links for bike enthusiasts.",
        features: [
          "Durable",
          "Unique design",
          "Lightweight",
          "Gift box included",
          "Rust-resistant",
        ],
        specifications: {
          Material: "Steel",
          Length: "6cm",
          Weight: "30g",
          Finish: "Chrome",
        },
        label: "POPULAR",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
        images: [
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "keychain-2",
        name: "Mini Helmet Keychain",
        title: "Mini Helmet Keychain",
        category: "keychains",
        price: 5.99,
        originalPrice: 7.99,
        discount: "25%",
        stockCount: 40,
        inStock: true,
        rating: 4.6,
        reviews: 45,
        description:
          "Miniature helmet keychain perfect for bike lovers and collectors.",
        features: [
          "Realistic design",
          "Lightweight",
          "Metal ring",
          "Colorful",
          "Collectible",
        ],
        specifications: {
          Material: "Plastic",
          Size: "3cm",
          Weight: "15g",
          Colors: "Multiple",
        },
        label: "NEW",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #43cea2 0%, #185a9d 100%)",
        images: [
          "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "keychain-3",
        name: "Leather Bike Keychain",
        title: "Leather Bike Keychain",
        category: "keychains",
        price: 8.99,
        originalPrice: 10.99,
        discount: "18%",
        stockCount: 30,
        inStock: true,
        rating: 4.5,
        reviews: 30,
        description:
          "Handcrafted leather keychain with bike charm for a premium look.",
        features: [
          "Handmade",
          "Genuine leather",
          "Bike charm",
          "Gift box",
          "Aged finish",
        ],
        specifications: {
          Material: "Leather",
          Length: "7cm",
          Weight: "20g",
          Style: "Vintage",
        },
        label: "SALE",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)",
        images: [
          "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "keychain-4",
        name: "Glow-in-the-Dark Keychain",
        title: "Glow-in-the-Dark Keychain",
        category: "keychains",
        price: 6.99,
        originalPrice: 8.99,
        discount: "22%",
        stockCount: 25,
        inStock: true,
        rating: 4.4,
        reviews: 20,
        description:
          "Keychain that glows in the dark for easy finding in low light.",
        features: [
          "Glows in dark",
          "Durable",
          "Lightweight",
          "Fun gift",
          "Long glow",
        ],
        specifications: {
          Material: "Plastic",
          Length: "5cm",
          Weight: "18g",
          Glow: "8 hours",
        },
        label: "HOT",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)",
        images: [
          "https://images.unsplash.com/photo-1519864600265-abb23847ef2c?w=600&h=600&fit=crop",
        ],
      },

      // TOYS CATEGORY
      {
        id: "toy-1",
        name: "Miniature Bike Toy",
        title: "Miniature Bike Toy",
        category: "toys",
        price: 12.99,
        originalPrice: 15.99,
        discount: "19%",
        stockCount: 35,
        inStock: true,
        rating: 4.8,
        reviews: 55,
        description:
          "Realistic miniature bike toy perfect for kids and collectors alike.",
        features: [
          "Metal frame",
          "Movable wheels",
          "Detailed design",
          "Safe paint",
          "Collectible",
        ],
        specifications: {
          Material: "Metal",
          Size: "10cm",
          Weight: "50g",
          Scale: "1:18",
        },
        label: "POPULAR",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
        images: [
          "https://images.unsplash.com/photo-1518655048521-f130df041f66?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "toy-2",
        name: "Pull-Back Bike Toy",
        title: "Pull-Back Bike Toy",
        category: "toys",
        price: 9.99,
        originalPrice: 12.99,
        discount: "23%",
        stockCount: 40,
        inStock: true,
        rating: 4.7,
        reviews: 40,
        description:
          "Fun pull-back action bike toy that provides hours of entertainment.",
        features: [
          "Pull-back action",
          "Colorful",
          "Safe for kids",
          "Durable",
          "Fast moving",
        ],
        specifications: {
          Material: "Plastic",
          Size: "8cm",
          Weight: "30g",
          Age: "3+",
        },
        label: "NEW",
        labelType: "premium",
        backgroundColor: "linear-gradient(135deg, #43cea2 0%, #185a9d 100%)",
        images: [
          "https://images.unsplash.com/photo-1465101178521-c1a9136a3b41?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "toy-3",
        name: "Bike Puzzle Toy",
        title: "Bike Puzzle Toy",
        category: "toys",
        price: 14.99,
        originalPrice: 18.99,
        discount: "21%",
        stockCount: 20,
        inStock: true,
        rating: 4.6,
        reviews: 25,
        description:
          "Challenging bike-shaped puzzle that provides brain-teasing fun for all ages.",
        features: [
          "Puzzle pieces",
          "Bike shape",
          "Colorful",
          "Brain teaser",
          "Educational",
        ],
        specifications: {
          Material: "Wood",
          Pieces: "50",
          Size: "15cm",
          Age: "6+",
        },
        label: "SALE",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
        images: [
          "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&h=600&fit=crop",
        ],
      },
      {
        id: "toy-4",
        name: "Wind-Up Bike Toy",
        title: "Wind-Up Bike Toy",
        category: "toys",
        price: 8.99,
        originalPrice: 10.99,
        discount: "18%",
        stockCount: 30,
        inStock: true,
        rating: 4.5,
        reviews: 18,
        description:
          "Classic wind-up bike toy that brings back nostalgic fun for everyone.",
        features: [
          "Wind-up action",
          "Classic design",
          "Safe for kids",
          "Durable",
          "Nostalgic",
        ],
        specifications: {
          Material: "Plastic",
          Size: "7cm",
          Weight: "25g",
          Age: "3+",
        },
        label: "HOT",
        labelType: "sale",
        backgroundColor: "linear-gradient(135deg, #00c6ff 0%, #0072ff 100%)",
        images: [
          "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=600&h=600&fit=crop",
        ],
      },
    ];

    // Insert all products
    await Product.insertMany(products);

    return NextResponse.json({
      success: true,
      message: "Products seeded successfully!",
      count: products.length,
      categories: [...new Set(products.map((p) => p.category))],
    });
  } catch (error) {
    console.error("Error seeding products:", error);
    return NextResponse.json(
      { error: "Failed to seed products" },
      { status: 500 }
    );
  }
}
